## SENSORS / LEGACY / GARAGE

# heating time on today
- platform: history_stats
  name: 'HVAC Garage Heating Time On Today'
  entity_id: binary_sensor.hvac_garage_heating_state
  state: 'on'
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# mean humidity from climate sensors:
#  - acurite 592TXR
#  - am2302 (wired dht22)
- platform: min_max
  name: 'Garage Mean Humidity Calculation'
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.snr_garage_climate_humidity
    - sensor.garage_vehicle_door_opener_am2301_humidity

# mean temperature from climate sensors:
#  - acurite 592TXR
#  - sinopé TH1400ZB
- platform: min_max
  name: 'Garage Mean Temperature Calculation'
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.snr_garage_climate_temperature
    - sensor.hvac_garage_thermostat_temperature
