## SENSORS / LEGACY / HOUSE

## hvac ecobee time on today
- platform: history_stats
  name: 'HVAC Ecobee Time On Today'
  entity_id: binary_sensor.hvac_ecobee_state
  state: 'on'
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# mean indoor air quality from awair sensors
- platform: min_max
  name: 'Indoor Mean Air Quality Calculation'
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.snr_familyroom_airquality_pm2_5
    - sensor.snr_mainbedroom_airquality_pm2_5
    - sensor.snr_office_airquality_pm2_5

# mean indoor Co2 levels from air quality sensors
- platform: min_max
  name: 'Indoor Mean Co2 Calculation'
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.snr_crawlspace_airquality_co2
    - sensor.snr_kidsbedroom_airquality_co2
    - sensor.snr_mainbedroom_airquality_co2
    - sensor.snr_office_airquality_cao2

# mean indoor humidity from climate sensors
- platform: min_max
  name: 'Indoor Mean Humidity Calculation'
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.hvac_ecobee_indoor_average_humidity
    - sensor.snr_crawlspace_climate_humidity
    - sensor.snr_office_airquality_humidity
    - sensor.snr_kitchen_airquality_humidity
    - sensor.snr_mainbedroom_airquality_humidity
    - sensor.snr_kidsbedroom_airquality_humidity
    - sensor.snr_sparebedroom_climate_humidity
