## SENSORS / LEGACY / HOUSE

## hvac ecobee time on today
- platform: history_stats
  name: 'HVAC Ecobee Time On Today'
  entity_id: binary_sensor.hvac_ecobee_state
  state: 'on'
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# mean indoor humidity from climate sensors
- platform: min_max
  name: 'Indoor Mean Humidity Calculation'
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.hvac_ecobee_indoor_average_humidity
    - sensor.snr_crawlspace_climate_humidity
    - sensor.snr_kitchen_climate_humidity
    - sensor.snr_office_humidity
    - sensor.snr_mainbedroom_climate_humidity
    - sensor.snr_kidsbedroom_climate_humidity
    - sensor.snr_sparebedroom_climate_humidity
