## SENSORS / LEGACY / KIDS BEDROOM

# mean temperature from climate sensors:
- platform: min_max
  name: 'Kids Bedroom Mean Temperature Calculation'
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.snr_kidsbedroom_climate_temperature
    - sensor.snr_kidsbedroom_climatedisplay_temperature
