## SENSORS / LEGACY / OFFICE

# mean air quality (2.5pm)
- platform: statistics
  name: "SNR Office Mean AirQuality PM 2_5"
  entity_id: sensor.snr_office_airquality_pm_2_5
  state_characteristic: mean
  max_age:
    minutes: 5
  sampling_size: 100
  precision: 1
