## SENSORS / LEGACY / OFFICE

# mean air quality (2.5pm)
- platform: statistics
  name: "SNR Office Mean AirQuality PM 2_5"
  entity_id: sensor.snr_office_airquality_pm_2_5
  state_characteristic: mean
  max_age:
    minutes: 5
  sampling_size: 100
  precision: 0

# -- xiaomi mi flora --
# dracaena trifasciata (also known as: sansevieria trifasciata)
- platform: miflora
  name: 'Plnt_Office Dracaena Trifasciata'
  mac: 'C4:7C:8D:6D:D0:E1'
  force_update: true
  median: 3
  go_unavailable_timeout: 43200
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery