## LIGHTS / FAMILY ROOM

# stairwell ceiling light (chandelier)
# *needed for EVENT command_topic due to multi-replay (3 ways switch)
- platform: mqtt
  name: "Stairwell Ceiling"
  state_topic: "stat/SW_StairwellCeiling/POWER1"
  command_topic: "cmnd/SW_StairwellCeiling/EVENT"
  availability_topic: "tele/SW_StairwellCeiling/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false