## LIGHTS / MAIN BEDROOM

# ceiling dimmer
- platform: mqtt
  name: "Main Bedroom Ceiling"
  state_topic: "stat/SW_MainBedroomCeiling/POWER"
  command_topic: "cmnd/SW_MainBedroomCeiling/POWER"
  availability_topic: "tele/SW_MainBedroomCeiling/LWT"
  brightness_state_topic: "stat/SW_MainBedroomCeiling/RESULT"
  brightness_command_topic: "cmnd/SW_MainBedroomCeiling/Dimmer"
  brightness_scale: 100
  brightness_value_template: >
    {% if value_json.Dimmer is defined %}
      {{ value_json.Dimmer }}
    {% else %}
      {% if state_attr('light.main_bedroom_ceiling','brightness') == none %}
        100
      {% else %}
        {{ state_attr('light.main_bedroom_ceiling','brightness') / 255 * 100 }}
      {% endif %}
    {% endif %}
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false