
## ha core configurations
default_config:
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url: !include assets/core/extra_modules.yaml
homeassistant:
  customize: !include_dir_merge_named assets/customize
# http
http: !include assets/core/http.yaml
# lovelace
lovelace: !include assets/core/lovelace.yaml

amcrest: !include_dir_merge_list assets/cameras/amcrest
automation: !include automations.yaml
binary_sensor: !include_dir_merge_list assets/binary_sensors/groups
camera: !include_dir_merge_list assets/cameras/generic
cover: !include_dir_merge_list assets/covers
group: !include groups.yaml
input_boolean: !include_dir_merge_named assets/input_booleans
input_datetime: !include_dir_merge_named assets/input_datetime
light: !include_dir_merge_list assets/lights/legacy
media_player: !include_dir_merge_list assets/media_players
mqtt: 
  light: !include_dir_merge_list assets/lights/mqtt
  sensor: !include_dir_merge_list assets/sensors/mqtt
  switch: !include_dir_merge_list assets/switches/mqtt
notify: !include notify.yaml
plant: !include_dir_merge_named assets/plants
scene: !include_dir_merge_list assets/scenes
script: !include_dir_merge_named assets/scripts
sensor: !include_dir_merge_list assets/sensors/legacy
switch: !include_dir_merge_list assets/switches/legacy
#template: !include_dir_merge_list assets/templates
template:
  binary_sensor: !include_dir_merge_list assets/binary_sensors/templates
  sensor: !include_dir_merge_list assets/sensors/templates
tts: !include assets/core/tts.yaml
