
## ha core configurations
default_config:
frontend:
  themes: !include_dir_merge_named themes
homeassistant:
  customize: !include_dir_merge_named assets/customize
# http
http: !include assets/core/http.yaml
# lovelace
lovelace: !include assets/core/lovelace.yaml


automation: !include automations.yaml
binary_sensor: !include_dir_merge_list assets/binary_sensors
camera: !include_dir_merge_list assets/cameras
cover: !include_dir_merge_list assets/covers
group: !include groups.yaml
input_boolean: !include_dir_merge_named assets/input_booleans
light: !include_dir_merge_list assets/lights
media_player: !include_dir_merge_list assets/media_players
notify: !include notify.yaml
plant: !include_dir_merge_named assets/plants
scene: !include_dir_merge_list assets/scenes
script: !include_dir_merge_named assets/scripts
sensor: !include_dir_merge_list assets/sensors
switch: !include_dir_merge_list assets/switches
template: !include_dir_merge_list assets/templates
tts: !include assets/core/tts.yaml
wake_on_lan:
webostv: !include_dir_merge_list assets/webostv

## hacs: hass-sensorpush
# https://github.com/rsnodgrass/hass-sensorpush
sensorpush:
  username: !secret sensorpush_username
  password: !secret sensorpush_password