
## ha core configurations
default_config:
frontend:
  themes: !include_dir_merge_named themes
homeassistant:
  customize: !include customize.yaml
# http
http: !include assets/core/http.yaml
# lovelace
lovelace: !include assets/core/lovelace.yaml


automation: !include automations.yaml
binary_sensor: !include_dir_merge_list assets/binary_sensors
cover: !include_dir_merge_list assets/covers
group: !include groups.yaml
light: !include_dir_merge_list assets/lights
scene: !include scenes.yaml
script: !include_dir_merge_named assets/scripts
sensor: !include_dir_merge_list assets/sensors
template: !include_dir_merge_list assets/templates

## hass-sensorpush
# https://github.com/rsnodgrass/hass-sensorpush
sensorpush:
  username: !secret sensorpush_username
  password: !secret sensorpush_password

# environment canada weather
weather:
  - platform: environment_canada
    station: !secret environment_canada_station

## text to speech
tts: !include assets/core/tts.yaml

## rtsp cameras
camera: !include_dir_merge_list assets/cameras