## COVERS / GARAGE

# custom sensors templates
- platform: template
  covers:
    # garage vehicle door opener
    garage_vehicledoor:
      friendly_name: 'Garage Door'
      device_class: garage
      value_template: >-
        {{ is_state('switch.sw_garage_vehicledoorcontact','on') }}
      open_cover:
        service: switch.turn_on
        entity_id: switch.sw_garage_vehicledooropener
      close_cover:
        service: switch.turn_on
        entity_id: switch.sw_garage_vehicledooropener
      icon_template: >-
        {% if is_state('switch.sw_garage_vehicledoorcontact','on') %}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}