blueprint:
  name: 'Tasmota Discovery: ZY-M100 mmWave Presence Sensor'
  source_url: https://github.com/tasmota/blueprints/blob/main/discovery_zy-m100.yaml
  description: "Set up a ZY-M100 mmWave Human Presence sensor running Tasmota in Home
    Assistant. See device template page for additional information: [ZY-M100](https://templates.blakadder.com/ZY-M100.html).\n\n**Configure
    Tasmota with template** \n```   \nTemplate {\"NAME\":\"ZY-M100\",\"GPIO\":[1,1,1,1,1,1,0,0,1,1,1,1,1,0],\"FLAG\":0,\"BASE\":54,\"CMND\":\"SO97
    1 | TuyaMCU 99,1 | TuyaMCU 75,104 | Rule3 1\"}\n```\n\n**Add rule in Tasmota**
    \n\n```   \nrule3\non tuyareceived#dptype4id1 do publish %topic%/presence %value%
    endon\non tuyareceived#dptype2id2 do publish %topic%/sensitivity %value% endon\non
    tuyareceived#dptype2id3 do publish %topic%/minrange %value% endon\non tuyareceived#dptype2id4
    do publish %topic%/maxrange %value% endon\non tuyareceived#dptype4id6 do publish
    %topic%/selfcheck %value% endon\non tuyareceived#dptype2id9 do publish %topic%/distance
    %value% endon\non tuyareceived#dptype2id101 do publish %topic%/detection_latency
    %value% endon\non tuyareceived#dptype2id102 do publish %topic%/hold_time %value%
    endon\non tuyareceived#dptype1id106 do publish %topic%/button pressed endon\n```
    \  \n\nReview and teardown of the device on [blakadder.com](https://blakadder.com/zy-m100/).\n\n<small>Built
    for Home Assistant 2022.11+</small>\n"
  domain: automation
  input:
    tasmota_device:
      name: Tasmota Device
      description: Select the Tasmota device
      selector:
        device:
          integration: tasmota
          manufacturer: Tasmota
          multiple: false
    topic:
      name: Tasmota MQTT Topic
      description: 'Found in the web UI "Information" menu under "MQTT Topic" or with
        `Topic` command

        '
      selector:
        text: {}
mode: single
max_exceeded: silent
variables:
  device_id: !input tasmota_device
  topic: !input topic
  connections: '{{ device_attr(device_id, ''connections'') }}'
  name: '{{ device_attr(device_id, ''name'') if device_attr(device_id, ''name_by_user'')
    == None else device_attr(device_id, ''name_by_user'') }}'
  macaddr: "{%- for i in device_attr(device_id, 'connections') -%}\n  {{ i[1].replace(\":\",
    \"\") }}\n{% endfor %}"
  payload_presence: "{{ \n  '{\n    \"name\":\"' ~ name ~ ' Presence\",\n    \"device_class\":\"occupancy\",\n
    \   \"state_topic\":\"' ~ topic ~ '/presence\",\n    \"payload_on\":\"1\",\n    \"payload_off\":\"0\",\n
    \   \"avty_t\":\"tele/' ~ topic ~ '/LWT\",\n    \"pl_avail\":\"Online\",\n    \"pl_not_avail\":\"Offline\",\n
    \   \"uniq_id\":\"' ~ macaddr ~ '_presence\",\n    \"dev\":{\"cns\":[[\"mac\",\"'
    ~ macaddr ~ '\"]]}\n  }' \n}}"
  payload_sensitivity: "{{ \n  '{\n    \"name\":\"' ~ name ~ ' Radar Sensitivity\",\n
    \   \"icon\":\"hass:radar\",\n    \"min\":\"0\",\n    \"max\":\"9\",\n    \"step\":\"1\",\n
    \   \"state_topic\":\"' ~ topic ~ '/sensitivity\",\n    \"command_topic\":\"cmnd/'
    ~ topic ~ '/tuyasend2\",\n    \"command_template\":\"2,{{ value }}\",\n    \"mode\":\"slider\",\n
    \   \"entity_category\":\"config\",\n    \"avty_t\":\"tele/' ~ topic ~ '/LWT\",\n
    \   \"pl_avail\":\"Online\",\n    \"pl_not_avail\":\"Offline\",\n    \"uniq_id\":\"'
    ~ macaddr ~ '_sensitivity\",\n    \"dev\":{\"cns\":[[\"mac\",\"' ~ macaddr ~ '\"]]}\n
    \ }' \n}}"
  payload_minrange: "{{ \n  '{\n    \"name\":\"' ~ name ~ ' Minimum Range\",\n    \"icon\":\"hass:magnify-minus-cursor\",\n
    \   \"min\":\"0\",\n    \"max\":\"10\",\n    \"step\":\"0.10\",\n    \"unit_of_measurement\":\"m\",\n
    \   \"state_topic\":\"' ~ topic ~ '/minrange\",\n    \"value_template\":\"{{ value
    | float * 0.01 }}\",\n    \"command_topic\":\"cmnd/' ~ topic ~ '/tuyasend2\",\n
    \   \"command_template\":\"3,{{ value | float * 100 }}\",\n    \"mode\":\"slider\",\n
    \   \"entity_category\":\"config\",\n    \"avty_t\":\"tele/' ~ topic ~ '/LWT\",\n
    \   \"pl_avail\":\"Online\",\n    \"pl_not_avail\":\"Offline\",\n    \"uniq_id\":\"'
    ~ macaddr ~ '_minrange\",\n    \"dev\":{\"cns\":[[\"mac\",\"' ~ macaddr ~ '\"]]}\n
    \ }' \n}}"
  payload_maxrange: "{{ \n  '{\n    \"name\":\"' ~ name ~ ' Maximum Range\",\n    \"icon\":\"hass:magnify-plus-cursor\",\n
    \   \"min\":\"0\",\n    \"max\":\"10\",\n    \"step\":\"0.10\",\n    \"unit_of_measurement\":\"m\",\n
    \   \"state_topic\":\"' ~ topic ~ '/maxrange\",\n    \"value_template\":\"{{ value
    | float * 0.01 }}\",\n    \"command_topic\":\"cmnd/' ~ topic ~ '/tuyasend2\",\n
    \   \"command_template\":\"4,{{ value | float * 100 }}\",\n    \"entity_category\":\"config\",\n
    \   \"mode\":\"slider\",\n    \"avty_t\":\"tele/' ~ topic ~ '/LWT\",\n    \"pl_avail\":\"Online\",\n
    \   \"pl_not_avail\":\"Offline\",\n    \"uniq_id\":\"' ~ macaddr ~ '_maxrange\",\n
    \   \"dev\":{\"cns\":[[\"mac\",\"' ~ macaddr ~ '\"]]}\n  }' \n}}"
  payload_selftest: "{{ \n  '{\n    \"name\":\"' ~ name ~ ' Self Test\",\n    \"icon\":\"hass:test-tube\",\n
    \   \"state_topic\":\"' ~ topic ~ '/selfcheck\",\n    \"value_template\":\"{%-
    set val = { \\'0\\':\\'Checking\\', \\'1\\':\\'Successful\\', \\'2\\':\\'Failure\\',
    \\'3\\':\\'Other\\', \\'4\\':\\'Communication Fault\\', \\'5\\':\\'Radar Fault\\'
    } -%}{{ val[value] | default(\\'Checking\\', true) }}\",\n    \"entity_category\":\"diagnostic\",\n
    \   \"enabled_by_default\":\"true\",\n    \"avty_t\":\"tele/' ~ topic ~ '/LWT\",\n
    \   \"pl_avail\":\"Online\",\n    \"pl_not_avail\":\"Offline\",\n    \"uniq_id\":\"'
    ~ macaddr ~ '_selfcheck\",\n    \"dev\":{\"cns\":[[\"mac\",\"' ~ macaddr ~ '\"]]}\n
    \ }' \n}}"
  payload_distance: "{{ \n  '{\n    \"name\":\"' ~ name ~ ' Target Distance\",\n    \"device_class\":\"distance\",\n
    \   \"state_topic\":\"' ~ topic ~ '/distance\",\n    \"value_template\":\"{{ value
    | float / 100 | default(0, true) }}\",\n    \"unit_of_measurement\":\"m\",\n    \"avty_t\":\"tele/'
    ~ topic ~ '/LWT\",\n    \"pl_avail\":\"Online\",\n    \"pl_not_avail\":\"Offline\",\n
    \   \"uniq_id\":\"' ~ macaddr ~ '_distance\",\n    \"dev\":{\"cns\":[[\"mac\",\"'
    ~ macaddr ~ '\"]]}\n  }' \n}}"
  payload_detectionlatency: "{{ \n  '{\n    \"name\":\"' ~ name ~ ' Detection Latency\",\n
    \   \"icon\":\"hass:timer-settings\",\n    \"min\":\"0\",\n    \"max\":\"10\",\n
    \   \"step\":\"0.10\",\n    \"unit_of_measurement\":\"s\",\n    \"state_topic\":\"'
    ~ topic ~ '/detection_latency\",\n    \"value_template\":\"{{ value | float *
    0.1 }}\",\n    \"command_topic\":\"cmnd/' ~ topic ~ '/tuyasend2\",\n    \"command_template\":\"101,{{
    value | float * 10 }}\",\n    \"mode\":\"slider\",\n    \"entity_category\":\"config\",\n
    \   \"avty_t\":\"tele/' ~ topic ~ '/LWT\",\n    \"pl_avail\":\"Online\",\n    \"pl_not_avail\":\"Offline\",\n
    \   \"uniq_id\":\"' ~ macaddr ~ '_detectionlatency\",\n    \"dev\":{\"cns\":[[\"mac\",\"'
    ~ macaddr ~ '\"]]}\n  }' \n}}"
  payload_holdtime: "{{ \n  '{\n    \"name\":\"' ~ name ~ ' Hold Time\",\n    \"icon\":\"hass:account-tie-voice-off\",\n
    \   \"min\":\"1\",\n    \"max\":\"1500\",\n    \"step\":\"1\",\n    \"unit_of_measurement\":\"s\",\n
    \   \"state_topic\":\"' ~ topic ~ '/hold_time\",\n    \"value_template\":\"{{
    value }}\",\n    \"command_topic\":\"cmnd/' ~ topic ~ '/tuyasend2\",\n    \"command_template\":\"102,{{
    value }}\",\n    \"mode\":\"box\",\n    \"entity_category\":\"config\",\n    \"avty_t\":\"tele/'
    ~ topic ~ '/LWT\",\n    \"pl_avail\":\"Online\",\n    \"pl_not_avail\":\"Offline\",\n
    \   \"uniq_id\":\"' ~ macaddr ~ '_holdtime\",\n    \"dev\":{\"cns\":[[\"mac\",\"'
    ~ macaddr ~ '\"]]}\n  }' \n}}"
  payload_button: "{{ \n  '{\n    \"automation_type\":\"trigger\",\n    \"topic\":\"'
    ~ topic ~ '/button\",\n    \"payload\":\"pressed\",\n    \"type\":\"button_short_press\",\n
    \   \"subtype\":\"reset_button\",\n    \"uniq_id\":\"' ~ macaddr ~ '_button\",\n
    \   \"dev\":{\"cns\":[[\"mac\",\"' ~ macaddr ~ '\"]]}\n  }' \n}}"
trigger_variables:
  topic: !input topic
trigger:
- platform: homeassistant
  event: start
- platform: mqtt
  topic: '{{ "tele/" ~ topic ~ "/LWT" }}'
  payload: Online
action:
- service: mqtt.publish
  data:
    topic: homeassistant/binary_sensor/{{ macaddr }}/presence/config
    retain: true
    payload: '{{ payload_presence }}'
- service: mqtt.publish
  data:
    topic: homeassistant/number/{{ macaddr }}/sensitivity/config
    retain: true
    payload: '{{ payload_sensitivity }}'
- service: mqtt.publish
  data:
    topic: homeassistant/number/{{ macaddr }}/minrange/config
    retain: true
    payload: '{{ payload_minrange }}'
- service: mqtt.publish
  data:
    topic: homeassistant/number/{{ macaddr }}/maxrange/config
    retain: true
    payload: '{{ payload_maxrange }}'
- service: mqtt.publish
  data:
    topic: homeassistant/sensor/{{ macaddr }}/distance/config
    retain: true
    payload: '{{ payload_distance }}'
- service: mqtt.publish
  data:
    topic: homeassistant/sensor/{{ macaddr }}/selftest/config
    retain: true
    payload: '{{ payload_selftest }}'
- service: mqtt.publish
  data:
    topic: homeassistant/number/{{ macaddr }}/detectiondelay/config
    retain: true
    payload: '{{ payload_detectionlatency }}'
- service: mqtt.publish
  data:
    topic: homeassistant/number/{{ macaddr }}/fadingtime/config
    retain: true
    payload: '{{ payload_holdtime }}'
- service: mqtt.publish
  data:
    topic: homeassistant/device_automation/{{ macaddr }}/button/config
    retain: true
    payload: '{{ payload_button }}'
- delay:
    hours: 0
    minutes: 0
    seconds: 5
    milliseconds: 0
- service: mqtt.publish
  data:
    topic: cmnd/{{ topic }}/tuyasend8
    payload: ''
