## SWITCHES / LEGACY / GARAGE

# house door lock
- platform: template
  switches:
    garage_house_door_lock:
      friendly_name: 'Garage House Door Lock'
      unique_id: sw_garage_house_door_lock
      # confirm door is locked
      value_template: >
        {{ is_state('lock.lck_garage_house_door', 'locked') }}
      turn_on:
        - action: lock.lock
          data: {}
          target:
            entity_id: lock.lck_garage_house_door
      turn_off:
        - action: lock.unlock
          data: {}
          target:
            entity_id: lock.lck_garage_house_door
      icon_template: >-
        {% if is_state('lock.lck_garage_house_door', 'on') %}
          mdi:lock-outline
        {% else %}
          mdi:lock-open-variant-outline
        {% endif %}

    # tv toggle
    sw_garage_entertainment:
      unique_id: sw_garage_entertainment
      # confirm tv is on
      value_template: >
        {{ is_state('media_player.garage_tv', 'on') }}
      turn_on:
        # turn on tv and switch app to plex through android tv remote
        - action: remote.turn_on
          data:
            activity: plex://
          target:
            entity_id: remote.garage_tv
      turn_off:
        # turn off tv through android tv remote
        - action: remote.turn_off
          data: {}
          target:
            entity_id: remote.garage_tv
