## SENSORS / LEGACY / HOUSE

# ALWAYS ON plugs
- platform: group
  name: 'Group Always On Plugs'
  all: true # group state should only turn on if all grouped entities are on
  entities:
    - switch.plg_crawlspace_deepfreezer
    - switch.plg_garage_fridge
    - switch.plg_laundry_washingmachine
    - switch.sw_livingroom_fireplace_fan

# front door lock
- platform: template
  switches:
    house_front_door_lock:
      friendly_name: 'House Front Door Lock'
      # confirm door is locked
      value_template: >
        {{ is_state('lock.lck_house_front_door', 'on') }}
      turn_on:
        - service: lock.lock
          data: {}
          target:
            entity_id: lock.lck_house_front_door
      turn_off:
        - service: lock.unlock
          data: {}
          target:
            entity_id: lock.lck_house_front_door
      icon_template: >-
        {% if is_state('lock.lck_house_front_door', 'on') %}
          mdi:lock-outline
        {% else %}
          mdi:lock-open-variant-outline
        {% endif %}
