## SWITCHES / LEGACY / LIVING ROOM

# tv & receiver on/off
- platform: template
  switches:
    living_room_enternainment:
      unique_id: living_room_entertainment
      value_template: >
        {{
          is_state('media_player.living_room_receiver_main_zone', 'on') and
          is_state('media_player.living_room_tv', 'on')
        }}
      turn_on:
        # send IR signal to toggle tv power
        - action: mqtt.publish
          data:
            topic: cmnd/IRB_LivingRoom/IRSend
            payload: >
              {"Protocol":"NEC","Bits":32,"Data":"0x20DF10EF","Repeat":0}
        # send IR signal to toggle receiver power
        - action: mqtt.publish
          data:
            topic: cmnd/IRB_LivingRoom/IRSend
            payload: >
              {"Protocol":"NEC","Bits":32,"Data":"0x7E8154AB","Repeat":0}
      turn_off:
        # send IR signal to toggle tv power
        - action: mqtt.publish
          data:
            topic: cmnd/IRB_LivingRoom/IRSend
            payload: >
              {"Protocol":"NEC","Bits":32,"Data":"0x20DF10EF","Repeat":0}
        # send IR signal to toggle receiver power
        - action: mqtt.publish
          data:
            topic: cmnd/IRB_LivingRoom/IRSend
            payload: >
              {"Protocol":"NEC","Bits":32,"Data":"0x7E8154AB","Repeat":0}

    living_room_entertainment_htcp:
      unique_id: living_room_entertainment_htpc
      # confirm tv and receiver is on
      value_template: >
        {{
          is_state('switch.living_room_entertainment', 'on') and
          is_state_attr('media_player.living_room_receiver_main_zone','source', 'AV2')
        }}
      turn_on:
        - action: switch.turn_on
          data:
            entity_id: switch.living_room_entertainment
        # ensure the correct sources are selected for htpc
        - delay: '00:00:02' # give devices a chance to start
        - action: media_player.select_source
          data:
            entity_id: media_player.living_room_tv
            source: "HDMI 4"
        - action: media_player.select_source
          data:
            entity_id: media_player.living_room_receiver_main_zone
            source: "AV2"
      turn_off:
        - action: switch.turn_off
          data:
            entity_id: switch.living_room_entertainment

    living_room_entertainment_nintendo:
      unique_id: living_room_entertainment_nintendo
      # confirm tv and receiver is on
      value_template: >
        {{
          is_state('switch.living_room_entertainment', 'on') and
          is_state_attr('media_player.living_room_receiver_main_zone','source', 'AV3')
        }}
      turn_on:
        - action: switch.turn_on
          data:
            entity_id: switch.living_room_entertainment
        # ensure the correct sources are selected for htpc
        - delay: '00:00:02' # give devices a chance to start
        - action: media_player.select_source
          data:
            entity_id: media_player.living_room_tv
            source: "HDMI 4"
        - action: media_player.select_source
          data:
            entity_id: media_player.living_room_receiver_main_zone
            source: "AV3"
      turn_off:
        - action: switch.turn_off
          data:
            entity_id: switch.living_room_entertainment