## SWITCHES / LEGACY / LIVING ROOM

# tv & receiver on/off
- platform: template
  switches:
    living_room_entertainment:
      # confirm tv and receiver is on
      value_template: >
        {{
          is_state('media_player.living_room_receiver_main_zone', 'on') and
          is_state('media_player.living_room_tv', 'on')
        }}
      turn_on:
        # turn devices on
        - service: wake_on_lan.send_magic_packet
          data:
            mac: !secret living_room_tv_mac
        - service: media_player.turn_on
          target:
            entity_id: media_player.living_room_receiver_main_zone
        # ensure the correct sources are selected for htpc
        - delay: '00:00:02' # give devices a chance to start
        - service: media_player.select_source
          data:
            entity_id: media_player.living_room_tv
            source: "HDMI 4"
        - service: media_player.select_source
          data:
            entity_id: media_player.living_room_receiver_main_zone
            source: "AV2"
      turn_off:
        - service: media_player.turn_off
          target:
            entity_id: media_player.living_room_tv
        - service: media_player.turn_off
          target:
            entity_id: media_player.living_room_receiver_main_zone
