## SWITCHES / LEGACY / MAIN BEDROOM

# tv on/off
- platform: template
  switches:
    main_bedroom_entertainment:
      # confirm tv is on
      value_template: >
        {{ is_state('media_player.main_bedroom_tv', 'on') }}
      turn_on:
        # turn devices on
        - service: mqtt.publish
          data:
            topic: cmnd/IRB_MainBedroom/IRSend
            payload: >
              {"Protocol":"NEC","Bits":32,"Data":"0x20DF10EF","DataLSB":"0x4FB08F7","Repeat":0}
        # ensure the correct sources are selected for htpc
        - delay: '00:00:02' # give devices a chance to start
        - service: media_player.select_source
          data:
            entity_id: media_player.main_bedroom_tv
            source: "HDMI 4"
        - service: media_player.select_source
          data:
            entity_id: media_player.main_bedroom_speaker
            source: "TV"
      turn_off:
        - service: mqtt.publish
          data:
            topic: cmnd/IRB_MainBedroom/IRSend
            payload: >
              {"Protocol":"NEC","Bits":32,"Data":"0x20DF10EF","DataLSB":"0x4FB08F7","Repeat":0}
