## SWITCHES / LEGACY / MAIN BEDROOM

- platform: template
  switches:
    # dyson air purifier toggle
    sw_main_bedroom_airpurifier:
      unique_id: sw_main_bedroom_airpurifier
      value_template: >
        {{
           is_state('climate.main_bedroom', 'cool') and
           is_state('fan.main_bedroom', 'on')
        }}
      turn_on:
        # set hvac mode to heat
        - service: climate.set_hvac_mode
          data:
            hvac_mode: cool
          target:
            entity_id: climate.main_bedroom
        # set fan speed to 20%
        - service: fan.set_percentage
          data:
            percentage: 20
          target:
            entity_id: fan.main_bedroom
      turn_off:
        # set hvac mode to cool
        - service: climate.set_hvac_mode
          data:
            hvac_mode: cool
          target:
            entity_id: climate.main_bedroom
        # turn off fan
        - service: fan.turn_off
          target:
            entity_id: fan.main_bedroom

    # dyson heater toggle
    sw_main_bedroom_heater:
      unique_id: sw_main_bedroom_heater
      value_template: >
        {{
           is_state('climate.main_bedroom', 'heat') and
           is_state('fan.main_bedroom', 'on')
        }}
      turn_on:
        # set hvac mode to heat
        - service: climate.set_temperature
          data:
            hvac_mode: heat
            temperature: 21
          target:
            entity_id: climate.main_bedroom
        # ensure fan gets turned on
        - service: fan.turn_on
          target:
            entity_id: fan.main_bedroom
      turn_off:
        # set hvac mode to cool
        - service: climate.set_hvac_mode
          data:
            hvac_mode: cool
          target:
            entity_id: climate.main_bedroom
        # run the fan for a bit to use the heat
        - delay: '00:00:10'
        # turn off fan
        - service: fan.turn_off
          target:
            entity_id: fan.main_bedroom

    # tv/sound bar toggle
    sw_main_bedroom_entertainment:
      unique_id: sw_main_bedroom_entertainment
      # confirm tv is on
      value_template: >
        {{ is_state('media_player.main_bedroom_tv', 'on') }}
      turn_on:
        # send IR signal to toggle tv power
        - service: mqtt.publish
          data:
            topic: cmnd/IRB_MainBedroom/IRSend
            payload: >
              {"Protocol":"NEC","Bits":32,"Data":"0x20DF10EF","DataLSB":"0x4FB08F7","Repeat":0}
        # ensure the correct sources are selected for htpc
        - delay: '00:00:02' # give devices a chance to start
        - service: media_player.select_source
          data:
            entity_id: media_player.main_bedroom_tv
            source: "HDMI 4"
        - service: media_player.select_source
          data:
            entity_id: media_player.main_bedroom_speaker
            source: "TV"
        # set volume on soundbar
        - service: media_player.volume_set
          data:
            volume_level: 0.13 # 13%
          target:
            entity_id: media_player.main_bedroom_speaker
      turn_off:
        # send IR signal to toggle tv power
        - service: mqtt.publish
          data:
            topic: cmnd/IRB_MainBedroom/IRSend
            payload: >
              {"Protocol":"NEC","Bits":32,"Data":"0x20DF10EF","DataLSB":"0x4FB08F7","Repeat":0}
