## SWITCHES / LEGACY / MAIN BEDROOM

# tv on/off
- platform: template
  switches:
    main_bedroom_entertainment:
      # confirm tv is on
      value_template: >
        {{ is_state('media_player.main_bedroom_tv', 'on') }}
      turn_on:
        # turn devices on
        - service: wake_on_lan.send_magic_packet
          data:
            mac: !secret main_bedroom_tv_mac
        # ensure the correct sources are selected for htpc
        - delay: '00:00:02' # give devices a chance to start
        - service: media_player.select_source
          data:
            entity_id: media_player.main_bedroom_tv
            source: "HDMI 4"
        - service: media_player.select_source
          data:
            entity_id: media_player.main_bedroom_speaker
            source: "TV"
      turn_off:
        - service: media_player.turn_off
          target:
            entity_id: media_player.main_bedroom_tv
