## SENSORS / CRAWLSPACE

# mean humidity from locker climate sensors:
#  - xiaomi aqara
#  - xiaomi mi
- platform: min_max
  name: 'Crawlspace Locker Mean Humidity Calculation'
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.snr_crawlspace_lockerclimate_humidity
    - sensor.snr_crawlspace_locker_climatedisplay_humidity

# -- LaCrosse TX141Bv3 (published by rtl_433) --
# deep freezer temperature
- platform: mqtt
  name: 'SNR Crawlspace Freezer Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  state_topic: rtl_433/sensor/LaCrosse-TX141Bv3-41
  json_attributes_topic: rtl_433/sensor/LaCrosse-TX141Bv3-41
  value_template: >
    {{ value_json.temperature_C | round(1, default=-15.0) }}

# -- Xiaomi Mi LYWSD03MMC (published by esphome ble bridge) --
# battery
- platform: mqtt
  name: 'SNR Crawlspace Locker ClimateDisplay Battery'
  device_class: battery
  unit_of_measurement: '%'
  state_topic: "esphome/house-ble-bridge/sensor/crawlspace_locker_battery_level/state"
  availability_topic: "esphome/house-ble-bridge/availability/status"

# humidity
- platform: mqtt
  name: 'SNR Crawlspace Locker ClimateDisplay Humidity'
  device_class: humidity
  unit_of_measurement: '%'
  state_topic: "esphome/house-ble-bridge/sensor/crawlspace_locker_humidity/state"
  availability_topic: "esphome/house-ble-bridge/availability/status"

# temperature
- platform: mqtt
  name: 'SNR Crawlspace Locker ClimateDisplay Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  state_topic: "esphome/house-ble-bridge/sensor/crawlspace_locker_temperature/state"
  availability_topic: "esphome/house-ble-bridge/availability/status"