## SENSORS / FAMILY ROOM

# -- xiaomi mi flora --
# parlor palm (chamaedorea elegans)
- platform: miflora
  name: 'Plnt_Family Room Parlor Palm'
  mac: 'C4:7C:8D:6C:E5:89'
  force_update: true
  median: 3
  go_unavailable_timeout: 43200
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery