## SENSORS / GARAGE

# heating time on today
- platform: history_stats
  name: 'HVAC Garage Heating Time On Today'
  entity_id: binary_sensor.hvac_garage_heating_state
  state: 'on'
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# mean humidity from climate sensors:
#  - xiaomi aqara
#  - am2302 (wired dht22)
- platform: min_max
  name: 'Garage Mean Humidity Calculation'
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.snr_garage_climate_humidity
    - sensor.garage_door_opener_am2301_humidity

# mean temperature from climate sensors:
#  - xiaomi aqara
#  - sinopé
- platform: min_max
  name: 'Garage Mean Temperature Calculation'
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.snr_garage_climate_temperature
    - sensor.hvac_garage_thermostat_temperature

# grab heating demand value from sinopé thermostat
- platform: mqtt
  name: 'HVAC Garage Heating Demand'
  availability:
    - topic: zigbee2mqtt-pi/bridge/state
  state_topic: zigbee2mqtt-pi/HVAC_GarageThermostat
  value_template: >
    {% if is_number(value_json.pi_heating_demand) %}
      {{ value_json.pi_heating_demand }}
    {% else %}
      0
    {% endif %}

# -- LaCrosse TX141Bv3 (published by rtl_433) --
# freezer
- platform: mqtt
  name: 'SNR Garage Freezer Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  state_topic: rtl_433/sensor/LaCrosse-TX141Bv3-74
  json_attributes_topic: rtl_433/sensor/LaCrosse-TX141Bv3-74
  value_template: >
    {{ value_json.temperature_C | round(1, default=-15.0) }}

# fridge
- platform: mqtt
  name: 'SNR Garage Fridge Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  state_topic: rtl_433/sensor/LaCrosse-TX141Bv3-57
  json_attributes_topic: rtl_433/sensor/LaCrosse-TX141Bv3-57
  value_template: >
    {{ value_json.temperature_C | round(1, default=1.0) }}