## SENSORS / GARAGE

# heating time on today
- platform: history_stats
  name: 'HVAC Garage Heating Time On Today'
  entity_id: sensor.hvac_garage_heating_state
  state: 'on'
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# mean humidity from climate sensors:
#  - xiaomi aqara
#  - am2302 (wired dht22)
- platform: min_max
  name: 'Garage Mean Humidity Calculation'
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.snr_garageclimate_humidity
    - sensor.garage_door_opener_am2301_humidity

# mean temperature from climate sensors:
#  - xiaomi aqara
#  - sinopé
- platform: min_max
  name: 'Garage Mean Temperature Calculation'
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.snr_garageclimate_temperature
    - sensor.hvac_garagethermostat_temperature

# grab heating demand value from sinopé thermostat
- platform: mqtt
  name: 'HVAC Garage Heating Demand'
  availability:
    - topic: zigbee2mqtt-pi/bridge/state
  state_topic: zigbee2mqtt-pi/HVAC_GarageThermostat
  value_template: >
    {% if is_number(value_json.pi_heating_demand) %}
      {{ value_json.pi_heating_demand }}
    {% else %}
      0
    {% endif %}