## SENSORS / KITCHEN

# -- LaCrosse TX141Bv3 (published by rtl_433) --
# freezer
- platform: mqtt
  name: 'SNR Kitchen Freezer Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  state_topic: rtl_433/sensor/LaCrosse-TX141Bv3-189
  json_attributes_topic: rtl_433/sensor/LaCrosse-TX141Bv3-189
  value_template: >
    {{ value_json.temperature_C | round(1, default=-15.0) }}

# fridge
- platform: mqtt
  name: 'SNR Kitchen Fridge Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  state_topic: rtl_433/sensor/LaCrosse-TX141Bv3-187
  json_attributes_topic: rtl_433/sensor/LaCrosse-TX141Bv3-187
  value_template: >
    {{ value_json.temperature_C | round(1, default=1.0) }}