## SENSORS / OFFICE

# mean air quality (2.5pm)
- platform: statistics
  name: "SNR Office Mean AirQuality PM 2_5"
  entity_id: sensor.snr_office_airquality_pm_2_5
  state_characteristic: mean
  max_age:
    minutes: 5
  sampling_size: 100
  precision: 0

# -- xiaomi mi flora --
# dracaena trifasciata (also known as: sansevieria trifasciata)
- platform: miflora
  name: 'Plnt_Office Dracaena Trifasciata'
  mac: 'C4:7C:8D:6D:D0:E1'
  force_update: true
  median: 3
  go_unavailable_timeout: 43200
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

# -- esphome --
# air quality
- platform: mqtt
  name: 'SNR Office AirQuality PM 2_5'
  device_class: pm25
  unit_of_measurement: "μg/m³"
  force_update: true
  state_topic: "esphome/snr-office-airquatliy/sensor/airquality_pm_25/state"
  availability_topic: "esphome/snr-office-airquatliy/availability/status"

# humidity
- platform: mqtt
  name: 'SNR Office Humidity'
  device_class: humidity
  unit_of_measurement: '%'
  state_topic: "esphome/snr-office-airquatliy/sensor/humidity/state"
  availability_topic: "esphome/snr-office-airquatliy/availability/status"

# temperature
- platform: mqtt
  name: 'SNR Office Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  state_topic: "esphome/snr-office-airquatliy/sensor/temperature/state"
  availability_topic: "esphome/snr-office-airquatliy/availability/status"