## SENSORS / OFFICE

# -- xiaomi mi flora --
# dracaena trifasciata (also known as: sansevieria trifasciata)
- platform: miflora
  name: 'Plnt_Office Dracaena Trifasciata'
  mac: 'C4:7C:8D:6D:D0:E1'
  force_update: true
  median: 3
  go_unavailable_timeout: 43200
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery