## SENSORS / OUTSIDE

# -- Acurite 592TXR (published by rtl_433) --
# temperature
- platform: mqtt
  name: 'SNR Outside Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  state_topic: rtl_433/sensor/Acurite-Tower-9142
  json_attributes_topic: rtl_433/sensor/Acurite-Tower-9142
  value_template: >
    {{ value_json.temperature_C | round(1, default=10.0) }}

# humidity
- platform: mqtt
  name: 'SNR Outside Humidity'
  device_class: humidity
  unit_of_measurement: '%'
  state_topic: rtl_433/sensor/Acurite-Tower-9142
  json_attributes_topic: rtl_433/sensor/Acurite-Tower-9142
  value_template: >
    {{ value_json.humidity | int(default=50) }}


# -- Purple Air (rest) --
- platform: rest
  name: 'PurpleAir'
  # purpleair sensor
  resource: https://www.purpleair.com/json?key=YY84TD217DXUVWTF&show=80563
  scan_interval: 120
  # code translated from JavaScript found at:
  #   https://docs.google.com/document/d/15ijz94dXJ-YAZLi9iZ_RaBwrZ4KtYeCy08goGBwnbCU
  value_template: >
    {% macro calcAQI(Cp, Ih, Il, BPh, BPl) %}
      {{ (((Ih - Il)/(BPh - BPl)) * (Cp - BPl) + Il) | round(1, default=0.0) }}
    {% endmacro %}
    {% if is_number(value_json["results"][0]["PM2_5Value"]) %}
      {% set pm25_value =  value_json["results"][0]["PM2_5Value"] | float %}
      {% if pm25_value > 1000 %}
        invalid
      {% elif pm25_value > 350.5 %}
        {{ calcAQI(pm25_value, 500.0, 401.0, 500.0, 350.5) }}
      {% elif pm25_value > 250.5 %}
        {{ calcAQI(pm25_value, 400.0, 301.0, 350.4, 250.5) }}
      {% elif pm25_value > 150.5 %}
        {{ calcAQI(pm25_value, 300.0, 201.0, 250.4, 150.5) }}
      {% elif pm25_value > 55.5 %}
        {{ calcAQI(pm25_value, 200.0, 151.0, 150.4, 55.5) }}
      {% elif pm25_value > 35.5 %}
        {{ calcAQI(pm25_value, 150.0, 101.0, 55.4, 35.5) }}
      {% elif pm25_value > 12.1 %}
        {{ calcAQI(pm25_value, 100.0, 51.0, 35.4, 12.1) }}
      {% elif pm25_value >= 0.0 %}
        {{ calcAQI(pm25_value, 50.0, 0.0, 12.0, 0.0) }}
      {% else %}
        invalid
      {% endif %}
    {% else %}
      invalid
    {% endif %}
  unit_of_measurement: "AQI"
  json_attributes:
    - results


# -- Toyota TPMS (reported by: rtl_433) --
# tire pressure (convert kPa to psi)
- platform: mqtt
  name: 'SNR Outside Tacoma TPMS1'
  device_class: pressure
  unit_of_measurement: psi
  force_update: true
  state_topic: rtl_433/sensor/Toyota-d8b4ed0a
  json_attributes_topic: rtl_433/sensor/Toyota-d8b4ed0a
  value_template: >
    {{ ( value_json.pressure_kPa * 0.145038) | round(1, default=0.0) }}

- platform: mqtt
  name: 'SNR Outside Tacoma TPMS2'
  device_class: pressure
  unit_of_measurement: psi
  force_update: true
  state_topic: rtl_433/sensor/Toyota-d8b7309e
  json_attributes_topic: rtl_433/sensor/Toyota-d8b7309e
  value_template: >
    {{ (value_json.pressure_kPa * 0.145038) | round(1, default=0.0) }}

- platform: mqtt
  name: 'SNR Outside Tacoma TPMS3'
  device_class: pressure
  unit_of_measurement: psi
  force_update: true
  state_topic: rtl_433/sensor/Toyota-d8b73111
  json_attributes_topic: rtl_433/sensor/Toyota-d8b73111
  value_template: >
    {{ (value_json.pressure_kPa * 0.145038) | round(1, default=0.0) }}

- platform: mqtt
  name: 'SNR Outside Tacoma TPMS4'
  device_class: pressure
  unit_of_measurement: psi
  force_update: true
  state_topic: rtl_433/sensor/Toyota-d8b4f5bf
  json_attributes_topic: rtl_433/sensor/Toyota-d8b4f5bf
  value_template: >
    {{ (value_json.pressure_kPa * 0.145038) | round(1, default=0.0) }}


# -- Xiaomi Mi LYWSD03MMC (published by esphome ble bridge) --
# battery
- platform: mqtt
  name: 'SNR Outside TacomaClimate Battery'
  device_class: battery
  unit_of_measurement: '%'
  state_topic: "esphome/home-front-ble-bridge/sensor/tacoma_battery_level/state"
  availability_topic: "esphome/home-front-ble-bridge/availability/status"

# humidity
- platform: mqtt
  name: 'SNR Outside TacomaClimate Humidity'
  device_class: humidity
  unit_of_measurement: '%'
  force_update: true
  state_topic: "esphome/home-front-ble-bridge/sensor/tacoma_humidity/state"
  availability_topic: "esphome/home-front-ble-bridge/availability/status"

# temperature
- platform: mqtt
  name: 'SNR Outside TacomaClimate Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  force_update: true
  state_topic: "esphome/home-front-ble-bridge/sensor/tacoma_temperature/state"
  availability_topic: "esphome/home-front-ble-bridge/availability/status"
