## SENSORS / OUTSIDE

# -- Acurite 592TXR (published by rtl_433) --
# temperature
- platform: mqtt
  name: 'SNR Outside Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  state_topic: rtl_433/sensor/Acurite-Tower-9142
  json_attributes_topic: rtl_433/sensor/Acurite-Tower-9142
  value_template: >
    {{ value_json.temperature_C | round(1, default=10.0) }}

# humidity
- platform: mqtt
  name: 'SNR Outside Humidity'
  device_class: humidity
  unit_of_measurement: '%'
  state_topic: rtl_433/sensor/Acurite-Tower-9142
  json_attributes_topic: rtl_433/sensor/Acurite-Tower-9142
  value_template: >
    {{ value_json.humidity | int(default=50) }}

# -- Purple Air (rest) --
# air quality 2.5pm
- platform: rest
  name: 'SNR Outside AirQuality PM 2_5'
  scan_interval: 120
  resource: !secret purple_air_json_url
  device_class: pm25
  unit_of_measurement: "μg/m³"
  value_template: >
      {% if is_number(value_json.pm2_5_atm) and is_number(value_json.pm2_5_atm_b) %}
        {{ (value_json.pm2_5_atm + value_json.pm2_5_atm_b)/2 | int(default=0) }}
      {% else %}
        {# return last value if sensor doesn't return a number #}
        {{ states('sensor.snr_outside_airquality_pm_2_5') }}
      {% endif %}

# mean air quality 2.5pm
- platform: statistics
  name: "SNR Outside Mean AirQuality PM 2_5"
  entity_id: sensor.snr_outside_airquality_pm_2_5
  state_characteristic: mean
  max_age:
    minutes: 6
  precision: 1