## SENSORS / SHED

# mean temperature from climate sensors:
#  - LaCrosse TX29IT
#  - xiaomi aqara
- platform: min_max
  name: 'Shed Mean Temperature Calculation'
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.snr_shed_temperature
    - sensor.snr_shed_climate_temperature

# -- LaCrosse TX29IT (published by rtl_433) --
# temperature
- platform: mqtt
  name: 'SNR Shed Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  state_topic: rtl_433/sensor/LaCrosse-TX29IT-17
  json_attributes_topic: rtl_433/sensor/LaCrosse-TX29IT-17
  value_template: >
    {{ value_json.temperature_C | round(1, default=10.0) }}