## SENSORS / TACOMA

# -- Xiaomi Mi LYWSD03MMC (published by esphome ble bridge) --
# tacoma :: box
# battery
- platform: mqtt
  name: 'SNR Outside TacomaBoxClimate Battery'
  device_class: battery
  unit_of_measurement: '%'
  state_topic: "esphome/home-front-ble-bridge/sensor/tacoma_box_battery_level/state"
  availability_topic: "esphome/home-front-ble-bridge/availability/status"

# humidity
- platform: mqtt
  name: 'SNR Outside TacomaBoxClimate Humidity'
  device_class: humidity
  unit_of_measurement: '%'
  force_update: true
  state_topic: "esphome/home-front-ble-bridge/sensor/tacoma_box_humidity/state"
  availability_topic: "esphome/home-front-ble-bridge/availability/status"

# temperature
- platform: mqtt
  name: 'SNR Outside TacomaBoxClimate Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  force_update: true
  state_topic: "esphome/home-front-ble-bridge/sensor/tacoma_box_temperature/state"
  availability_topic: "esphome/home-front-ble-bridge/availability/status"

# tacoma :: cab
# battery
- platform: mqtt
  name: 'SNR Outside TacomaCabClimate Battery'
  device_class: battery
  unit_of_measurement: '%'
  state_topic: "esphome/home-front-ble-bridge/sensor/tacoma_cab_battery_level/state"
  availability_topic: "esphome/home-front-ble-bridge/availability/status"

# humidity
- platform: mqtt
  name: 'SNR Outside TacomaCabClimate Humidity'
  device_class: humidity
  unit_of_measurement: '%'
  force_update: true
  state_topic: "esphome/home-front-ble-bridge/sensor/tacoma_cab_humidity/state"
  availability_topic: "esphome/home-front-ble-bridge/availability/status"

# temperature
- platform: mqtt
  name: 'SNR Outside TacomaCabClimate Temperature'
  device_class: temperature
  unit_of_measurement: '°C'
  force_update: true
  state_topic: "esphome/home-front-ble-bridge/sensor/tacoma_cab_temperature/state"
  availability_topic: "esphome/home-front-ble-bridge/availability/status"
