## GARAGE

# custom sensors templates
- platform: template
  sensors:
    # -- xiaomi aqara --
    # climate sensor
    garage_temperature_f1:
      friendly_name: 'Garage Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_garageclimate_temperature") | round(1) }}'   
    garage_humidity_int:
      friendly_name: 'Garage Humidity integer'
      unit_of_measurement: '%'
      value_template: '{{ states("sensor.snr_garageclimate_humidity") | int }}'

    # -- sonoff --
    # garage door (vehicle) contact state
    garage_door_contact_state:
      friendly_name: 'Garage Door Contact state'
      value_template: >-
        {% if states('switch.sw_garagedoorcontact') == 'on' %}
          Open
        {% else %}
          Closed
        {% endif %}

    # garage door (vehicle) contact boolean
    garage_door_contact_bool:
      friendly_name: 'Garage Door Contact boolean'
      value_template: >-
        {% if states('switch.sw_garagedoorcontact') == 'on' %}
          1
        {% else %}
          0
        {% endif %}

    # garage dehumidifier (switch)
    garage_dehumidifier_bool:
      friendly_name: 'Garage Dehumidifier boolean'
      # power reported in watts
      value_template: >-
        {% if (states('sensor.garage_dehumidifier_plug_energy_power') | int) > 10 %}
          1
        {% else %}
          0
        {% endif %}

    # -- sinopé --
- platform: template
  sensors:
    # garage temperature
    hvac_garage_temperature:
      friendly_name: 'HVAC Garage Temperature'
      unit_of_measurement: '°C'
      device_class: temperature
      value_template: "{{ state_attr('climate.hvac_garagethermostat', 'current_temperature') }}"
    
    # heating on/off
    #  - state: used for alerts dashboard
    #  - bool:  used to annotate climate graphs
    hvac_garage_heating_state:
      friendly_name: 'HVAC Garage Heating state'
      value_template: >-
        {% if (state_attr('climate.hvac_garagethermostat', 'pi_heating_demand') | int) > 0 %}
          on
        {% else %}
          off
        {% endif %}
    hvac_garage_heating_bool:
      friendly_name: 'HVAC Garage Heating boolean'
      value_template: >-
        {% if (state_attr('climate.hvac_garagethermostat', 'pi_heating_demand') | int) > 0 %}
          1
        {% else %}
          0
        {% endif %}

# heating time on today
- platform: history_stats
  name: 'HVAC Garage Heating Time On Today'
  entity_id: sensor.hvac_garage_heating_state
  state: 'on'
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"