## KITCHEN

# custom sensors templates
- platform: template
  sensors:
    # -- sensor push --
    # climate sensor
    fridge_temperature_f1:
      friendly_name: 'Fridge Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.fridge_temperature") | round(1) }}'
    fridge_humidity_int:
      friendly_name: 'Fridge Humidity without decimal'
      unit_of_measurement: '%'
      value_template: '{{ states("sensor.fridge_humidity") | int }}'
    fridge_sensor_battery_voltage:
      friendly_name: 'Fridge SensorPush battery voltage'
      unit_of_measurement: 'V'
      value_template: '{{ state_attr("sensor.fridge_humidity", "battery_voltage") }}'