## LAUNDRY ROOM

# custom sensors templates
- platform: template
  sensors:
    # -- xiaomi aqara --
    # climate sensor
    laundry_temperature_f1:
      friendly_name: 'Laundry Room Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_laundryclimate_temperature") | round(1) }}'