## MAIN BEDROOM

# custom sensors templates
- platform: template
  sensors:
    # -- xiaomi aqara --
    # climate sensor
    main_bedroom_temperature_f1:
      friendly_name: 'Main Bedroom Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_mainbedroomclimate_temperature") | round(1) }}'