## OFFICE

# custom sensors templates
- platform: template
  sensors:
    # -- xiaomi aqara --
    # climate sensor
    office_temperature_f1:
      friendly_name: 'Office Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_officeclimate_temperature") | round(1) }}'