## hass-sensorpush
# https://github.com/rsnodgrass/hass-sensorpush
- platform: sensorpush

- platform: template
  sensors:
    # (deep) freezer
    freezer_temperature_f1:
      friendly_name: 'Freezer Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.freezer_temperature") | round(1) }}'
    freezer_humidity_int:
      friendly_name: 'Freezer Humidity without decimal'
      unit_of_measurement: '%'
      value_template: '{{ states("sensor.freezer_humidity") | int }}'
    freezer_sensor_battery_voltage:
      friendly_name: 'freezer SensorPush battery voltage'
      unit_of_measurement: 'V'
      value_template: '{{ state_attr("sensor.freezer_humidity", "battery_voltage") }}'

    # kitchen fridge
    fridge_temperature_f1:
      friendly_name: 'Fridge Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.fridge_temperature") | round(1) }}'
    fridge_humidity_int:
      friendly_name: 'Fridge Humidity without decimal'
      unit_of_measurement: '%'
      value_template: '{{ states("sensor.fridge_humidity") | int }}'
    fridge_sensor_battery_voltage:
      friendly_name: 'Fridge SensorPush battery voltage'
      unit_of_measurement: 'V'
      value_template: '{{ state_attr("sensor.fridge_humidity", "battery_voltage") }}'