- platform: template
  sensors:
    ## -- energy sensors --

    # deep freezer today total (2 decimals)
    deep_freezer_plug_energy_today_f2:
      friendly_name: 'Deep Freezer Plug Energy Today 2 decimal places'
      unit_of_measurement: 'kWh'
      value_template: '{{ states("sensor.deep_freezer_plug_energy_today") | round(2) }}'
    
    # deep freezer current (2 decimals)
    deep_freezer_plug_energy_current_f2:
      friendly_name: 'Deep Freezer Plug Energy Current 2 decimal places'
      unit_of_measurement: 'A'
      value_template: '{{ states("sensor.deep_freezer_plug_energy_current") | round(2) }}'

    # espresso machine today total (2 decimals)
    espresso_machine_plug_energy_today_f2:
      friendly_name: 'Espresso Machine Plug Energy Today 2 decimal places'
      unit_of_measurement: 'kWh'
      value_template: '{{ states("sensor.espresso_machine_plug_energy_today") | round(2) }}'
    
    # espresso machine current (2 decimals)
    espresso_machine_plug_energy_current_f2:
      friendly_name: 'Espresso Machine Plug Energy Current 2 decimal places'
      unit_of_measurement: 'A'
      value_template: '{{ states("sensor.espresso_machine_plug_energy_current") | round(2) }}'
    
    # garage dehumidifier today total (2 decimals)
    garage_dehumidifier_plug_energy_today_f2:
      friendly_name: 'Garage Dehumidifier Plug Energy Today 2 decimal places'
      unit_of_measurement: 'kWh'
      value_template: '{{ states("sensor.garage_dehumidifier_plug_energy_today") | round(2) }}'

    # garage dehumidifier current (2 decimals)
    garage_dehumidifier_plug_energy_current_f2:
      friendly_name: 'Garage Dehumidifier Plug Energy Current 2 decimal places'
      unit_of_measurement: 'A'
      value_template: '{{ states("sensor.garage_dehumidifier_plug_energy_current") | round(2) }}'
    

    ## -- other sensors --

    # garage door (vehicle) contact state
    garage_door_contact_state:
      friendly_name: 'Garage Door Contact state'
      value_template: >-
        {% if states('switch.sw_garagedoorcontact') == 'on' %}
          Open
        {% else %}
          Closed
        {% endif %}

    # garage door (vehicle) contact boolean
    garage_door_contact_bool:
      friendly_name: 'Garage Door Contact boolean'
      value_template: >-
        {% if states('switch.sw_garagedoorcontact') == 'on' %}
          1
        {% else %}
          0
        {% endif %}

    # garage dehumidifier (switch)
    garage_dehumidifier_bool:
      friendly_name: 'Garage Dehumidifier boolean'
      # power reported in watts
      value_template: >-
        {% if (states('sensor.garage_dehumidifier_plug_energy_power') | int) > 10 %}
          1
        {% else %}
          0
        {% endif %}