## SPARE BEDROOM

# custom sensors templates
- platform: template
  sensors:
    # -- xiaomi aqara --
    # climate sensor
    sparebedroom_temperature_f1:
      friendly_name: 'Spare Bedroom Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_sparebedroomclimate_temperature") | round(1) }}'