- platform: template
  sensors:
    ## -- battery level motion sensors --
    # garage outside (side door) motion sensor
    garage_outside_motion_battery:
      friendly_name: 'Garage Outside Motion Sensor Battery Level'
      unit_of_measurement: '%'
      value_template: '{{ state_attr("binary_sensor.wyzesense_77a7a16f","battery_level") }}'

    # front yard motion sensor
    front_yard_motion_battery:
      friendly_name: 'Front Yard Motion Sensor Battery Level'
      unit_of_measurement: '%'
      value_template: '{{ state_attr("binary_sensor.wyzesense_779f1f3a","battery_level") }}'


    ## -- battery level contact sensors --
    
    # garage door (vehicle) contact sensor
    garage_door_contact_battery:
      friendly_name: 'Garage Door Contact Sensor Battery Level'
      unit_of_measurement: '%'
      value_template: '{{ state_attr("binary_sensor.wyzesense_77a05475","battery_level") }}'