## aqara / xiaomi sensors

- platform: template
  sensors:
    # crawlspace
    crawlspace_temperature_f1:
      friendly_name: 'Crawlspace Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_crawlspaceclimate_temperature") | round(1) }}'      

    # garage
    garage_temperature_f1:
      friendly_name: 'Garage Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_garageclimate_temperature") | round(1) }}'   
    garage_humidity_int:
      friendly_name: 'Garage Humidity integer'
      unit_of_measurement: '%'
      value_template: '{{ states("sensor.snr_garageclimate_humidity") | int }}'

    # kids room
    kids_room_temperature_f1:
      friendly_name: 'Kids Room Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_kidsroomclimate_temperature") | round(1) }}'

    # laundry room
    laundry_temperature_f1:
      friendly_name: 'Laundry Room Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_laundryclimate_temperature") | round(1) }}'
    
    # main bedroom
    main_bedroom_temperature_f1:
      friendly_name: 'Main Bedroom Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_mainbedroomclimate_temperature") | round(1) }}'

    # office
    office_temperature_f1:
      friendly_name: 'Office Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_officeclimate_temperature") | round(1) }}'

    # shed
    shed_temperature_f1:
      friendly_name: 'Shed Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_shedclimate_temperature") | round(1) }}'   
    shed_humidity_int:
      friendly_name: 'Shed Humidity integer'
      unit_of_measurement: '%'
      value_template: '{{ states("sensor.snr_shedclimate_humidity") | int }}'

    # spare bedroom
    sparebedroom_temperature_f1:
      friendly_name: 'Spare Bedroom Temperature 1 decimal'
      unit_of_measurement: '°C'
      value_template: '{{ states("sensor.snr_sparebedroomclimate_temperature") | round(1) }}'