## LIGHTS / OUTSIDE

# driveway light bulb group
- platform: group
  name: 'Group Driveway Lights'
  entities:
    - light.blb_outside_driveway_left
    - light.blb_outside_driveway_right

# porch light bulb group
- platform: group
  name: 'Group Porch Lights'
  entities:
    - light.blb_outside_frontporch_left
    - light.blb_outside_frontporch_right
