- platform: template

  covers:
    # garage vehicle door opener
    garage_door:
      friendly_name: 'Garage Door'
      device_class: garage
      value_template: "{{ is_state('switch.sw_garagedoorcontact','on') }}"
      open_cover:
        service: switch.turn_on
        entity_id: switch.sw_garagedooropener
      close_cover:
        service: switch.turn_on
        entity_id: switch.sw_garagedooropener
      icon_template: >-
        {% if is_state('switch.sw_garagedoorcontact','on') %}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}