- platform: template

  covers:
    # garage door opener
    garage_door:
      friendly_name: 'Garage Door'
      device_class: garage
      value_template: "{{ is_state('binary_sensor.wyzesense_77a05475','on') }}"
      open_cover:
        service: switch.turn_on
        entity_id: switch.sw_garagedooropener1
      close_cover:
        service: switch.turn_on
        entity_id: switch.sw_garagedooropener1
      icon_template: >-
        {% if is_state('binary_sensor.wyzesense_77a05475','on') %}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}