substitutions:
  device_name: home-front-ble-bridge
  
esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO # DEBUG

ota:
  password: !secret home_front_ble_bridge_ota_passwd

# Set up Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: !secret home_front_ble_bridge_ip
    gateway: !secret network_gateway
    subnet: !secret network_subnet

# Enable MQTT Client
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: false
  topic_prefix: esphome/${device_name}
  birth_message:
    topic: esphome/${device_name}/availability/status
    payload: online
  will_message:
    topic: esphome/${device_name}/availability/status
    payload: offline

# Enable Bluetooth Low Energy Tracker Hub
esp32_ble_tracker:

sensor:
  # temperature :: truck
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:15:AF:5B"
    temperature:
      name: "Tacoma Temperature"
    humidity:
      name: "Tacoma Humidity"
    battery_level:
      name: "Tacoma Battery Level"
    battery_voltage:
      name: "Tacoma Battery Voltage"
    signal_strength:
      name: "Tacoma Signal"

  # temperature :: main bedroom
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:B3:0C:55"
    temperature:
      name: 'Main Bedroom Temperature'
    humidity:
      name: "Main Bedroom Humidity"
    battery_level:
      name: "Main Bedroom Battery Level"
    battery_voltage:
      name: "Main Bedroom Battery Voltage"
    signal_strength:
      name: "Main Bedroom Signal"

  # temperature :: crawlspace locker
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:5A:25:8A"
    temperature:
      name: 'Crawlspace Locker Temperature'
    humidity:
      name: "Crawlspace Locker Humidity"
    battery_level:
      name: "Crawlspace Locker Battery Level"
    battery_voltage:
      name: "Crawlspace Locker Battery Voltage"
    signal_strength:
      name: "Crawlspace Locker Signal"