substitutions:
  device_name: home-front-ble-bridge
  
esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO # DEBUG

ota:
  password: !secret home_front_ble_bridge_ota_passwd

# Set up Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: !secret home_front_ble_bridge_ip
    gateway: !secret network_gateway
    subnet: !secret network_subnet

# Home Assistant API
api:

# Enable Bluetooth Low Energy Tracker Hub
esp32_ble_tracker:

sensor:
  ## --- plants ---
  # family room: parlor palm
  - platform: xiaomi_hhccjcy01
    mac_address: "C4:7C:8D:6C:E5:89"
    conductivity:
      name: "SNR Family Room Parlor Palm Conductivity"
    illuminance:
      name: "SNR Family Room Parlor Palm Illuminance"
    moisture:
      name: "SNR Family Room Parlor Palm Moisture"
    temperature:
      name: "SNR Family Room Parlor Palm Temperature"

  # office: dracaena trifasciata
  - platform: xiaomi_hhccjcy01
    mac_address: "C4:7C:8D:6D:D0:E1"
    conductivity:
      name: "SNR Office Dracaena Trifasciata Conductivity"
    illuminance:
      name: "SNR Office Dracaena Trifasciata Illuminance"
    moisture:
      name: "SNR Office Dracaena Trifasciata Moisture"
    temperature:
      name: "SNR Office Dracaena Trifasciata Temperature"

  ## --- temperature ---
  # crawlspace: locker
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:5A:25:8A"
    temperature:
      name: "SNR Crawlspace Locker ClimateDisplay Temperature"
    humidity:
      name: "SNR Crawlspace Locker ClimateDisplay Humidity"
    battery_level:
      name: "SNR Crawlspace Locker ClimateDisplay Battery"
#    battery_voltage:
#      name: "SNR Crawlspace Locker ClimateDisplay Battery Voltage"
    signal_strength:
      name: "Crawlspace Locker Signal"

  # main bedroom
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:B3:0C:55"
    temperature:
      name: 'SNR MainBedroom ClimateDisplay Temperature'
    humidity:
      name: "SNR MainBedroom ClimateDisplay Humidity"
    battery_level:
      name: "SNR MainBedroom ClimateDisplay Battery"
#    battery_voltage:
#      name: "SNR MainBedroom ClimateDisplay Battery Voltage"
    signal_strength:
      name: "SNR MainBedroom ClimateDisplay Signal"

  # tacoma: box
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:F9:93:1B"
    temperature:
      name: "SNR Outside TacomaBoxClimate Temperature"
    humidity:
      name: "SNR Outside TacomaBoxClimate Humidity"
    battery_level:
      name: "SNR Outside TacomaBoxClimate Battery"
#    battery_voltage:
#      name: "SNR Outside TacomaBoxClimate Battery Voltage"
    signal_strength:
      name: "SNR Outside TacomaBoxClimate Signal"

  # tacoma: cab
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:15:AF:5B"
    temperature:
      name: "SNR Outside TacomaCabClimate Temperature"
    humidity:
      name: "SNR Outside TacomaCabClimate Humidity"
    battery_level:
      name: "SNR Outside TacomaCabClimate Battery"
#    battery_voltage:
#      name: "SNR Outside TacomaCabClimate Battery Voltage"
    signal_strength:
      name: "SNR Outside TacomaCabClimate Signal"