substitutions:
  device_name: home-front-ble-bridge
  
esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO # DEBUG

ota:
  password: !secret home_front_ble_bridge_ota_passwd

# Set up Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: !secret home_front_ble_bridge_ip
    gateway: !secret network_gateway
    subnet: !secret network_subnet

# Enable MQTT Client
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: false
  topic_prefix: esphome/${device_name}
  birth_message:
    topic: esphome/${device_name}/availability/status
    payload: online
  will_message:
    topic: esphome/${device_name}/availability/status
    payload: offline

# Enable Bluetooth Low Energy Tracker Hub
esp32_ble_tracker:

sensor:
  ## --- plants ---
  # family room: parlor palm
  - platform: xiaomi_hhccjcy01
    mac_address: "C4:7C:8D:6C:E5:89"
    conductivity:
      name: "Family Room Parlor Palm Conductivity"
    illuminance:
      name: "Family Room Parlor Palm Illuminance"
    moisture:
      name: "Family Room Parlor Palm Moisture"
    temperature:
      name: "Family Room Parlor Palm Temperature"

  # office: dracaena trifasciata
  - platform: xiaomi_hhccjcy01
    mac_address: "C4:7C:8D:6D:D0:E1"
    conductivity:
      name: "Office Dracaena Trifasciata Conductivity"
    illuminance:
      name: "Office Dracaena Trifasciata Illuminance"
    moisture:
      name: "Office Dracaena Trifasciata Moisture"
    temperature:
      name: "Office Dracaena Trifasciata Temperature"

  ## --- temperature ---
  # crawlspace: locker
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:5A:25:8A"
    temperature:
      name: "Crawlspace Locker Temperature"
    humidity:
      name: "Crawlspace Locker Humidity"
    battery_level:
      name: "Crawlspace Locker Battery Level"
    battery_voltage:
      name: "Crawlspace Locker Battery Voltage"
    signal_strength:
      name: "Crawlspace Locker Signal"

  # main bedroom
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:B3:0C:55"
    temperature:
      name: 'Main Bedroom Temperature'
    humidity:
      name: "Main Bedroom Humidity"
    battery_level:
      name: "Main Bedroom Battery Level"
    battery_voltage:
      name: "Main Bedroom Battery Voltage"
    signal_strength:
      name: "Main Bedroom Signal"

  # tacoma: box
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:F9:93:1B"
    temperature:
      name: "Tacoma Box Temperature"
    humidity:
      name: "Tacoma Box Humidity"
    battery_level:
      name: "Tacoma Box Battery Level"
    battery_voltage:
      name: "Tacoma Box Battery Voltage"
    signal_strength:
      name: "Tacoma Box Signal"

  # tacoma: cab
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:15:AF:5B"
    temperature:
      name: "Tacoma Cab Temperature"
    humidity:
      name: "Tacoma Cab Humidity"
    battery_level:
      name: "Tacoma Cab Battery Level"
    battery_voltage:
      name: "Tacoma Cab Battery Voltage"
    signal_strength:
      name: "Tacoma Cab Signal"