substitutions:
  name: office-ir-blaster
  friendly_name: Office IR Blaster

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp_wroom_02
  board_flash_mode: dout

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret irb_office_api_key

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_password_iot

  ap:
    ssid: "Office IR Fallback"
    password: !secret office_ir_blaster_fallback_password

captive_portal:

remote_transmitter:
  id: ir_transmitter
  pin: GPIO14
  carrier_duty_percent: 50%

infrared:
  - platform: ir_rf_proxy
    name: IR Transmitter
    id: infrared_transmitter
    remote_transmitter_id: ir_transmitter

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic

ota:
  - platform: esphome
    id: irb_office_ota
    password: !secret irb_office_ota_passwd
