substitutions:
  device_name: "office-environment"
  location: "Office"

esphome:
  name: ${device_name}

esp8266:
  board: nodemcuv2

# Set up Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # static ip assignment
  manual_ip:
    static_ip: !secret snr_office_airquality_ip
    gateway: !secret network_gateway
    subnet: !secret network_subnet

# Enable logging
logger:
  level: INFO # DEBUG for sensor readings

# Enable OTA updates
ota:
  password: !secret snr_office_airquatliy_ota_password

# Home Assistant API
api:

uart:
  tx_pin: D6
  rx_pin: D7
  baud_rate: 9600

switch:
  - platform: gpio
    pin: D3
    id: pms_set
    name: "SW Office AirQuality Measure"

interval:
  - interval: 120s
    then:
      - switch.turn_on: pms_set
      - delay: 20s
      - switch.turn_off: pms_set

sensor:
  # air quality
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "SNR Office AirQuality PM 1_0"
      filters:
        - sliding_window_moving_average:   
            window_size: 10
            send_every: 10
    pm_2_5:
      name: "SNR Office AirQuality PM 2_5"
      filters:
        - sliding_window_moving_average:   
            window_size: 10
            send_every: 10
#    pm_10_0:
#      name: "SNR Office AirQuality PM 10_0"
#      filters:
#        - sliding_window_moving_average:   
#            window_size: 10
#            send_every: 10

  # temperature/humidity
  - platform: dht
    model: AM2302
    pin: D4
    temperature:
      name: "SNR Office Temperature"
    humidity:
      name: "SNR Office Humidity"
    update_interval: 120s