substitutions:
  device_name: snr-mainbedroom-presence
  device_description: "Tuya ZY-M100 Human Presence Sensor"
  friendly_name: "Main Bedroom Presence Sensor"
  main_device_id: "snr_mainbedroom_presence" # Put the name that you want to see in Home Assistant.
  project_name: "tuya.zy-m100-wifi-esp-idf"
  project_version: "1.0"

esphome:
  name: ${device_name}
  comment: ${device_description}
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0
  level: INFO # DEBUG for sensor readings

# Enable Home Assistant API
api:
  encryption:
    key: !secret snr_mainbedroom_presence_key

ota:
  password: "1af51b4bb38f863aa1da39beab5454fc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: !secret snr_mainbedroom_presence_ip
    gateway: !secret network_gateway
    subnet: !secret network_subnet

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

# Register the Tuya MCU connection
tuya:

sensor:
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${friendly_name} Signal strength
    update_interval: 60s
    internal: true
  
  # Light Sensor
  #- platform: tuya
  #  name: "${friendly_name} Light Intensity"
  #  id: light_intensity
  #  sensor_datapoint: 104
  #  unit_of_measurement: "lux"
  #  icon: "mdi:brightness-5"
  #  device_class: "illuminance"
  #  state_class: "measurement"
  
  # Distance from Detected Object
  - platform: "tuya"
    name: "${friendly_name} Target Distance"
    id: target_distance
    sensor_datapoint: 9
    unit_of_measurement: "cm"
    icon: "mdi:arrow-left-right"
    device_class: "distance"
    state_class: "measurement"

text_sensor:
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP
    ssid:
      name: ${friendly_name} SSID
    bssid:
      name: ${friendly_name} BSSID

# Restart Buttons
button:
  - platform: restart
    id: "restart_device"
    name: "${friendly_name} Restart"
    entity_category: "diagnostic"
  - platform: safe_mode
    id: "restart_device_safe_mode"
    name: "${friendly_name} Restart (Safe Mode)"
    entity_category: "diagnostic"
number:
  # Sensitivity
  - platform: "tuya"
    name: "${friendly_name} Sensitivity"
    number_datapoint: 2
    min_value: 0
    max_value: 9
    step: 1
    icon: "mdi:radar"
  # Min Detection Distance
  - platform: "tuya"
    name: "${friendly_name} Min Range"
    number_datapoint: 3
    min_value: 0
    max_value: 1000
    step: 1
    mode: slider
    unit_of_measurement: "cm"
    icon: "mdi:magnify-minus-cursor"
  # Max Detection Distance
  - platform: "tuya"
    name: "${friendly_name} Max Range"
    number_datapoint: 4
    min_value: 0
    max_value: 1000
    step: 1
    mode: slider
    unit_of_measurement: "cm"
    icon: "mdi:magnify-plus-cursor"
  # Detection Delay
  - platform: "tuya"
    name: "${friendly_name} Detection Delay"
    number_datapoint: 101
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "s"
    mode: slider
    icon: "mdi:timer-settings-outline"
  # Fading Time - Cool Down Period
  - platform: "tuya"
    name: "${friendly_name} Cool Down Time"
    number_datapoint: 102
    min_value: 0
    max_value: 1500
    step: 1
    unit_of_measurement: "s"
    mode: slider
    icon: "mdi:account-clock-outline"

binary_sensor:
  # Status
  - platform: status
    name: "${friendly_name} Status"
  # Occupancy Binary Sensor
  - platform: "tuya"
    name: "${friendly_name} Presence"
    sensor_datapoint: 1
    device_class: occupancy
    icon: "mdi:home"