substitutions:
  device_name: snr-office-airquatliy
  location: "Office"

esphome:
  name: ${device_name}

esp8266:
  board: nodemcuv2

# Set up Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # static ip assignment
  manual_ip:
    static_ip: !secret snr_office_airquality_ip
    gateway: !secret network_gateway
    subnet: !secret network_subnet

# Enable logging
logger:
  level: INFO # DEBUG for sensor readings

# Enable OTA updates
ota:
  password: !secret snr_office_airquatliy_ota_password

# Enable MQTT Client
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: false
  topic_prefix: esphome/${device_name}
  birth_message:
    topic: esphome/${device_name}/availability/status
    payload: online
  will_message:
    topic: esphome/${device_name}/availability/status
    payload: offline

uart:
  tx_pin: D6
  rx_pin: D7
  baud_rate: 9600

switch:
  - platform: gpio
    pin: D3
    id: pms_set
    name: "AirQuality Measure"

interval:
  - interval: 120s
    then:
      - switch.turn_on: pms_set
      - delay: 20s
      - switch.turn_off: pms_set

sensor:
  # air quality
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "AirQuality PM 1.0"
      filters:
        - throttle_average: 60s
    pm_2_5:
      name: "AirQuality PM 2.5"
      filters:
        - throttle_average: 60s
    pm_10_0:
      name: "AirQuality PM 10.0"
      filters:
        - throttle_average: 60s

  # temperature/humidity
  - platform: dht
    model: AM2302
    pin: D4
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 120s